// packages/svelte/src/components/Progress.svelte
<script lang="ts">
  import { onDestroy, onMount } from 'svelte';
  import { createProgress } from '@guideloop/vanilla';
  import type { Theme, ThemeConfig } from '@guideloop/vanilla';

  export let current = 1;
  export let total = 1;
  export let theme: Theme = 'tailwind';
  export let customTheme: Partial<ThemeConfig> | undefined = undefined;

  let host: HTMLDivElement;
  let progress: ReturnType<typeof createProgress> | null = null;

  onMount(() => {
    progress = createProgress({
      current,
      total,
      theme,
      customTheme,
    });
    progress.mount(host);
  });

  $: if (progress) {
    progress.update(current, total);
  }

  onDestroy(() => {
    progress?.destroy();
    progress = null;
  });
</script>

<div class="guideloop-svelte-progress-host" bind:this={host} />

<style>
  .guideloop-svelte-progress-host {
    display: contents;
  }
</style>

// packages/angular/src/progress.component.ts
import {
  Component,
  ElementRef,
  Input,
  OnChanges,
  OnDestroy,
  OnInit,
  SimpleChanges,
  ViewChild,
} from '@angular/core';
import { createProgress } from '@guideloop/vanilla';
import type { Theme, ThemeConfig } from '@guideloop/vanilla';

/**
 * Standalone progress dots indicator.
 */
@Component({
  selector: 'guideloop-progress',
  standalone: true,
  template: `<div #host class="guideloop-angular-progress-host"></div>`,
  styles: [
    `
      :host {
        display: block;
      }
      .guideloop-angular-progress-host {
        display: contents;
      }
    `,
  ],
})
export class ProgressComponent implements OnInit, OnChanges, OnDestroy {
  @ViewChild('host', { static: true }) host!: ElementRef<HTMLDivElement>;

  @Input() current = 1;
  @Input() total = 1;
  @Input() theme: Theme = 'tailwind';
  @Input() customTheme: Partial<ThemeConfig> | undefined;

  private progress: ReturnType<typeof createProgress> | null = null;

  ngOnInit(): void {
    this.progress = createProgress({
      current: this.current,
      total: this.total,
      theme: this.theme,
      customTheme: this.customTheme,
    });
    this.progress.mount(this.host.nativeElement);
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (!this.progress) return;
    if (changes['current'] || changes['total']) {
      this.progress.update(this.current, this.total);
    }
  }

  ngOnDestroy(): void {
    this.progress?.destroy();
    this.progress = null;
  }
}
